#!/bin/bash

function echo_usage()
{
  echo "Usage: $(basename "$0") name"
  echo "A shorthand version of ssh using a name instead of adress."
  echo " "
  echo "  name: PC | RPI | localPC | localRPI | localRPI2"
  exit
}

if [ $# -ne 1 ]; then
  echo_usage
else
  case "$1" in
  "PC") ssh andy@78.73.34.221 -p 922;;
  "RPI") ssh pi@78.73.34.221 -p 22;;
  "localPC") ssh andy@192.168.1.167 -p 922;;
  "localRPI") ssh pi@192.168.1.172 -p 22;;
  "localRPI2") ssh pi@192.168.1.173 -p 22;;
  *) echo_usage
  esac
fi
